/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeRouteRouteImport } from './routes/theme/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemeIndexRouteImport } from './routes/theme/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as DocsGettingStartedIndexRouteImport } from './routes/docs/getting-started/index'
import { Route as ThemeDesignTokensRefrenceColorsIndexRouteImport } from './routes/theme/design-tokens/refrence-colors/index'

const ThemeRouteRoute = ThemeRouteRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeIndexRoute = ThemeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemeRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedIndexRoute = DocsGettingStartedIndexRouteImport.update({
  id: '/docs/getting-started/',
  path: '/docs/getting-started/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeDesignTokensRefrenceColorsIndexRoute =
  ThemeDesignTokensRefrenceColorsIndexRouteImport.update({
    id: '/design-tokens/refrence-colors/',
    path: '/design-tokens/refrence-colors/',
    getParentRoute: () => ThemeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theme': typeof ThemeRouteRouteWithChildren
  '/components': typeof ComponentsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/theme/': typeof ThemeIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/theme/design-tokens/refrence-colors': typeof ThemeDesignTokensRefrenceColorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/theme': typeof ThemeIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/theme/design-tokens/refrence-colors': typeof ThemeDesignTokensRefrenceColorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theme': typeof ThemeRouteRouteWithChildren
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/theme/': typeof ThemeIndexRoute
  '/docs/getting-started/': typeof DocsGettingStartedIndexRoute
  '/theme/design-tokens/refrence-colors/': typeof ThemeDesignTokensRefrenceColorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/theme'
    | '/components'
    | '/docs'
    | '/theme/'
    | '/docs/getting-started'
    | '/theme/design-tokens/refrence-colors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/docs'
    | '/theme'
    | '/docs/getting-started'
    | '/theme/design-tokens/refrence-colors'
  id:
    | '__root__'
    | '/'
    | '/theme'
    | '/components/'
    | '/docs/'
    | '/theme/'
    | '/docs/getting-started/'
    | '/theme/design-tokens/refrence-colors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemeRouteRoute: typeof ThemeRouteRouteWithChildren
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsGettingStartedIndexRoute: typeof DocsGettingStartedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/': {
      id: '/theme/'
      path: '/'
      fullPath: '/theme/'
      preLoaderRoute: typeof ThemeIndexRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started/': {
      id: '/docs/getting-started/'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/design-tokens/refrence-colors/': {
      id: '/theme/design-tokens/refrence-colors/'
      path: '/design-tokens/refrence-colors'
      fullPath: '/theme/design-tokens/refrence-colors'
      preLoaderRoute: typeof ThemeDesignTokensRefrenceColorsIndexRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
  }
}

interface ThemeRouteRouteChildren {
  ThemeIndexRoute: typeof ThemeIndexRoute
  ThemeDesignTokensRefrenceColorsIndexRoute: typeof ThemeDesignTokensRefrenceColorsIndexRoute
}

const ThemeRouteRouteChildren: ThemeRouteRouteChildren = {
  ThemeIndexRoute: ThemeIndexRoute,
  ThemeDesignTokensRefrenceColorsIndexRoute:
    ThemeDesignTokensRefrenceColorsIndexRoute,
}

const ThemeRouteRouteWithChildren = ThemeRouteRoute._addFileChildren(
  ThemeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemeRouteRoute: ThemeRouteRouteWithChildren,
  ComponentsIndexRoute: ComponentsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsGettingStartedIndexRoute: DocsGettingStartedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
