import { formatHex, parse } from "culori";
import type { SpecData } from "../types/index.js";

interface CSSOptions {
    palette?: string;
}

/**
 * Format spec data as CSS custom properties
 * Outputs base tokens (1-12, a1-a12) and semantic tokens
 */
export function formatCSS(specs: SpecData, options: CSSOptions = {}): string {
    const lines: string[] = [];
    const targetPalettes = options.palette ? [options.palette] : ["mori", "umi"];

    lines.push("/* Chlorophyll Design Tokens - Generated by @chlorophyll/cli */");
    lines.push("");

    // ===============================
    // Base Tokens (Reference Tokens)
    // ===============================
    lines.push("/* ===== Base Tokens (Reference Tokens) ===== */");
    lines.push(":root {");

    // Find colors category from tokens
    const colorsCategory = specs.tokens.data.find((cat) => cat.type === "colors");

    if (colorsCategory) {
        for (const palette of targetPalettes) {
            lines.push(`  /* ${palette} palette - light mode */`);

            // Light 1-12
            for (let i = 1; i <= 12; i++) {
                const token = colorsCategory.values.find((t) => t.name === `${palette}.light.${i}`);
                if (token) {
                    const hexValue = convertToHex(String(token.value));
                    lines.push(`  --mpc-colors-${palette}-light-${i}: ${hexValue};`);
                }
            }

            // Light a1-a12
            for (let i = 1; i <= 12; i++) {
                const token = colorsCategory.values.find((t) => t.name === `${palette}.light.a${i}`);
                if (token) {
                    const hexValue = convertToHex(String(token.value));
                    lines.push(`  --mpc-colors-${palette}-light-a${i}: ${hexValue};`);
                }
            }

            lines.push("");
        }
    }

    lines.push("}");
    lines.push("");

    // ===============================
    // Semantic Tokens
    // ===============================
    lines.push("/* ===== Semantic Tokens ===== */");
    lines.push(":root {");

    // Find semantic colors
    const semanticColorsCategory = specs.semanticTokens.data.find((cat) => cat.type === "colors");

    if (semanticColorsCategory) {
        for (const palette of targetPalettes) {
            lines.push(`  /* ${palette} palette semantic tokens - light */`);

            // 1-12 mapped to light tokens
            for (let i = 1; i <= 12; i++) {
                lines.push(`  --mpc-colors-${palette}-${i}: var(--mpc-colors-${palette}-light-${i});`);
            }

            // a1-a12 mapped to light tokens
            for (let i = 1; i <= 12; i++) {
                lines.push(`  --mpc-colors-${palette}-a${i}: var(--mpc-colors-${palette}-light-a${i});`);
            }

            lines.push("");

            // Semantic tokens (bg, fg, solid, etc.)
            const paletteTokens = semanticColorsCategory.values.filter(
                (t) => t.name.startsWith(`${palette}.`) && !t.name.match(/^\w+\.\d+$/) && !t.name.match(/^\w+\.a\d+$/),
            );

            for (const token of paletteTokens) {
                // Extract the semantic part (e.g., "mori.bg" -> "bg")
                const semanticName = token.name.replace(`${palette}.`, "");
                const cssVarName = `--mpc-colors-${palette}-${semanticName.replace(/\./g, "-")}`;

                // Light mode only: token values are flat, so only the base condition exists
                const baseCondition = token.values.find((v) => v.condition === "base");
                const value = baseCondition?.value || "";

                // Convert reference to CSS variable
                const cssValue = convertReferenceToVar(value, palette);
                lines.push(`  ${cssVarName}: ${cssValue};`);
            }

            lines.push("");
        }
    }

    lines.push("}");
    lines.push("");

    // ===============================
    // colorPalette Semantic Tokens
    // ===============================
    lines.push("/* ===== colorPalette Semantic Tokens ===== */");
    lines.push("/* Use these with colorPalette prop in components */");

    for (const palette of targetPalettes) {
        lines.push(`[data-color-palette='${palette}'] {`);

        // 1-12
        for (let i = 1; i <= 12; i++) {
            lines.push(`  --mpc-colors-color-palette-${i}: var(--mpc-colors-${palette}-${i});`);
        }

        // a1-a12
        for (let i = 1; i <= 12; i++) {
            lines.push(`  --mpc-colors-color-palette-a${i}: var(--mpc-colors-${palette}-a${i});`);
        }

        // Semantic colorPalette tokens
        const semanticNames = [
            "bg",
            "bg-subtle",
            "bg-secondary",
            "surface",
            "surface-hover",
            "surface-active",
            "fg",
            "fg-subtle",
            "fg-muted",
            "fg-secondary",
            "solid",
            "solid-emphasized",
            "contrast",
        ];

        for (const name of semanticNames) {
            lines.push(`  --mpc-colors-color-palette-${name}: var(--mpc-colors-${palette}-${name});`);
        }

        lines.push("}");
        lines.push("");
    }

    return lines.join("\n");
}

/**
 * Convert any color format to hex
 */
function convertToHex(value: string): string {
    const trimmed = value.trim();

    if (trimmed.startsWith("#")) {
        return trimmed;
    }

    try {
        const parsed = parse(trimmed);
        if (parsed) {
            const hex = formatHex(parsed);
            if (hex) {
                return hex;
            }
        }
    } catch {
        // If parsing fails, return original value
    }

    return trimmed;
}

/**
 * Convert token reference to CSS variable
 * e.g., "{colors.mori.2}" -> "var(--mpc-colors-mori-2)"
 */
function convertReferenceToVar(value: string, _palette: string): string {
    if (!value.startsWith("{") || !value.endsWith("}")) {
        // Direct value (like "#ffffff")
        return convertToHex(value);
    }

    // Extract reference path: "{colors.mori.2}" -> "colors.mori.2"
    const refPath = value.slice(1, -1);
    const parts = refPath.split(".");

    // Remove "colors." prefix if present
    if (parts[0] === "colors") {
        parts.shift();
    }

    // Convert to CSS variable format
    const varName = parts.join("-");
    return `var(--mpc-colors-${varName})`;
}
