import type { SpecData } from "../types/index.js";

/**
 * Fumadocs CSS variable mappings
 * Maps --color-fd-* variables to --mpc-colors-color-palette-* variables
 */
const FUMADOCS_MAPPINGS: Record<string, string> = {
    // Background colors
    "--color-fd-background": "var(--mpc-colors-color-palette-bg-subtle)",
    "--color-fd-background-muted": "var(--mpc-colors-color-palette-bg)",
    "--color-fd-secondary": "var(--mpc-colors-color-palette-surface)",
    "--color-fd-secondary-hover": "var(--mpc-colors-color-palette-surface-hover)",

    // Foreground colors
    "--color-fd-foreground": "var(--mpc-colors-color-palette-fg)",
    "--color-fd-muted-foreground": "var(--mpc-colors-color-palette-fg-muted)",
    "--color-fd-secondary-foreground": "var(--mpc-colors-color-palette-fg-subtle)",

    // Accent colors
    "--color-fd-primary": "var(--mpc-colors-color-palette-palette-fg)",
    "--color-fd-primary-foreground": "var(--mpc-colors-color-palette-fg-subtle)",

    // Card
    "--color-fd-card": "var(--mpc-colors-color-palette-bg-subtle)",
    "--color-fd-card-foreground": "var(--mpc-colors-color-palette-fg)",

    // Popover
    "--color-fd-popover": "var(--mpc-colors-color-palette-bg)",
    "--color-fd-popover-foreground": "var(--mpc-colors-color-palette-fg)",

    // Accent
    "--color-fd-accent": "var(--mpc-colors-color-palette-surface)",
    "--color-fd-accent-foreground": "var(--mpc-colors-color-palette-fg)",

    // Ring
    "--color-fd-ring": "var(--mpc-colors-color-palette-surface-hover)",
};

interface FumaDocsOptions {
    palette?: string;
}

/**
 * Format spec data as Fumadocs-compatible CSS
 * Generates CSS variable mappings for Fumadocs theming
 */
export function formatFumaDocs(specs: SpecData, options: FumaDocsOptions = {}): string {
    // Get available palettes from color-palette spec
    const availablePalettes = specs.colorPalette.data.values
        .filter((v) => !v.includes("."))
        .filter((v) => ["mori", "umi", "gray", "red", "yellow", "blue"].includes(v));

    // Use specified palette or default to mori and umi
    const requestedPalettes = options.palette ? [options.palette] : ["mori", "umi"];

    // Filter to only include available palettes
    const palettes = requestedPalettes.filter((p) => availablePalettes.includes(p));

    const lines: string[] = ["/* Generated by @chlorophyll/cli */", "/* Fumadocs CSS variable mappings */", ""];

    // Generate :root and default palette (mori)
    const defaultPalette = palettes[0] || "mori";
    lines.push(`:root, [data-color-palette='${defaultPalette}'] {`);
    lines.push(...generateMappingLines());
    lines.push("}");
    lines.push("");

    // Generate additional palette selectors
    for (const palette of palettes.slice(1)) {
        lines.push(`[data-color-palette='${palette}'] {`);
        lines.push("    /* color-palette automatically switches via Panda CSS */");
        lines.push("}");
        lines.push("");
    }

    return lines.join("\n");
}

/**
 * Generate CSS property lines for Fumadocs mappings
 */
function generateMappingLines(): string[] {
    const lines: string[] = [];

    // Group mappings by category
    const categories = {
        "Background colors": [
            "--color-fd-background",
            "--color-fd-background-muted",
            "--color-fd-secondary",
            "--color-fd-secondary-hover",
        ],
        "Foreground colors": [
            "--color-fd-foreground",
            "--color-fd-muted-foreground",
            "--color-fd-secondary-foreground",
        ],
        "Accent colors": ["--color-fd-primary", "--color-fd-primary-foreground"],
        Card: ["--color-fd-card", "--color-fd-card-foreground"],
        Popover: ["--color-fd-popover", "--color-fd-popover-foreground"],
        Accent: ["--color-fd-accent", "--color-fd-accent-foreground"],
        Ring: ["--color-fd-ring"],
    };

    for (const [category, vars] of Object.entries(categories)) {
        lines.push(`    /* ${category} */`);
        for (const varName of vars) {
            const value = FUMADOCS_MAPPINGS[varName];
            if (value) {
                lines.push(`    ${varName}: ${value};`);
            }
        }
        lines.push("");
    }

    // Remove trailing empty line
    if (lines[lines.length - 1] === "") {
        lines.pop();
    }

    return lines;
}
