import { formatHex, parse } from "culori";
import type { SpecData, W3CToken, W3CTokenGroup } from "../types/index.js";

/**
 * Panda CSS token type to W3C type mapping
 */
const TYPE_MAPPING: Record<string, string> = {
    colors: "color",
    spacing: "dimension",
    sizes: "dimension",
    fontSizes: "dimension",
    fontWeights: "fontWeight",
    lineHeights: "number",
    letterSpacings: "dimension",
    borderWidths: "dimension",
    radii: "dimension",
    durations: "duration",
    shadows: "shadow",
    zIndex: "number",
    opacity: "number",
    aspectRatios: "string",
    easings: "cubicBezier",
};

interface W3COptions {
    palette?: string;
}

/**
 * Format spec data as W3C Design Tokens 2025.10 format
 * @see https://www.designtokens.org/tr/2025.10/format/
 */
export function formatW3C(specs: SpecData, options: W3COptions = {}): string {
    const result: W3CTokenGroup = {
        $description: "Chlorophyll Design Tokens - Generated by @chlorophyll/cli",
    };

    // Process reference tokens
    for (const category of specs.tokens.data) {
        const w3cType = TYPE_MAPPING[category.type] || "string";

        // Initialize category group if not exists
        if (!result[category.type]) {
            result[category.type] = {
                $type: w3cType,
            } as W3CTokenGroup;
        }

        for (const token of category.values) {
            // Filter by palette if specified (only for colors)
            if (options.palette && category.type === "colors") {
                if (!token.name.includes(options.palette) && token.name !== "white" && token.name !== "black") {
                    continue;
                }
            }

            const pathParts = token.name.split(".");
            const w3cToken: W3CToken = {
                $value: parseValue(token.value, w3cType),
                $type: w3cType,
                $extensions: {
                    "com.chlorophyll": {
                        cssVariable: token.cssVar,
                    },
                },
            };

            setNestedValue(result[category.type] as W3CTokenGroup, pathParts, w3cToken);
        }
    }

    // Process semantic tokens
    const semanticGroup: W3CTokenGroup = {
        $description: "Semantic tokens with conditional values",
    };

    for (const category of specs.semanticTokens.data) {
        const w3cType = TYPE_MAPPING[category.type] || "string";

        if (!semanticGroup[category.type]) {
            semanticGroup[category.type] = {
                $type: w3cType,
            } as W3CTokenGroup;
        }

        for (const token of category.values) {
            // Filter by palette if specified
            if (options.palette && category.type === "colors") {
                if (!token.name.startsWith(`${options.palette}.`)) {
                    continue;
                }
            }

            const pathParts = token.name.split(".");

            // Handle conditional values
            const baseValue = token.values.find((v) => v.condition === "base");
            const rawValue = baseValue?.value || token.values[0]?.value || "";

            // Check if value is a reference (e.g., "{colors.gray.1}") or literal
            const isReference = typeof rawValue === "string" && rawValue.startsWith("{") && rawValue.endsWith("}");
            const parsedValue = isReference ? rawValue : parseValue(rawValue, w3cType);

            const w3cToken: W3CToken = {
                $value: parsedValue,
                $type: w3cType,
                $extensions: {
                    "com.chlorophyll": {
                        cssVariable: token.cssVar,
                        conditions: token.values.reduce(
                            (acc, v) => {
                                acc[v.condition] = v.value;
                                return acc;
                            },
                            {} as Record<string, string>,
                        ),
                    },
                },
            };

            setNestedValue(semanticGroup[category.type] as W3CTokenGroup, pathParts, w3cToken);
        }
    }

    result.semantic = semanticGroup;

    return JSON.stringify(result, null, 2);
}

/**
 * Parse a token value based on its W3C type
 */
function parseValue(value: string | number, type: string): unknown {
    // If value is already a number for numeric types, return it
    if (typeof value === "number") {
        if (type === "fontWeight" || type === "number") {
            return value;
        }
    }

    const strValue = String(value);

    switch (type) {
        case "color":
            return parseColorValue(strValue);
        case "dimension":
            return parseDimensionValue(strValue);
        case "number":
            return parseNumberValue(strValue);
        case "fontWeight":
            return parseFontWeightValue(value);
        case "duration":
            return parseDurationValue(strValue);
        case "cubicBezier":
            return parseCubicBezierValue(strValue);
        default:
            return value;
    }
}

/**
 * Parse color values to W3C Design Tokens 2025.10 format
 * @see https://www.designtokens.org/tr/2025.10/color/
 *
 * W3C 2025.10 specifies $value should be a string like "#ffffff" or "oklch(0.995 0.0033 165.1)"
 */
function parseColorValue(value: string): string {
    const trimmed = value.trim();

    // Already hex format - return as-is
    if (trimmed.startsWith("#")) {
        return trimmed;
    }

    try {
        const parsed = parse(trimmed);
        if (parsed) {
            // Convert any color format to hex string
            const hex = formatHex(parsed);
            if (hex) {
                return hex;
            }
        }
    } catch {
        // If parsing fails, return original value
    }

    return trimmed;
}

/**
 * Parse dimension values
 */
function parseDimensionValue(value: string): unknown {
    const match = value.match(/^([\d.]+)(rem|px|em|%|vh|vw)?$/);
    if (match) {
        const [, num, unit] = match;
        return {
            value: parseFloat(num),
            unit: unit || "px",
        };
    }
    return value;
}

/**
 * Parse number values
 */
function parseNumberValue(value: string): number | string {
    const num = parseFloat(value);
    return Number.isNaN(num) ? value : num;
}

/**
 * Parse font weight values
 */
function parseFontWeightValue(value: string | number): number | string {
    // If already a number, return it
    if (typeof value === "number") {
        return value;
    }

    const weights: Record<string, number> = {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
        black: 900,
    };

    const lower = value.toLowerCase();
    if (lower in weights) {
        return weights[lower];
    }

    const num = parseInt(value, 10);
    return Number.isNaN(num) ? value : num;
}

/**
 * Parse duration values
 */
function parseDurationValue(value: string): unknown {
    const match = value.match(/^([\d.]+)(ms|s)?$/);
    if (match) {
        const [, num, unit] = match;
        const numVal = parseFloat(num);
        const ms = unit === "s" ? numVal * 1000 : numVal;
        return {
            value: ms,
            unit: "ms",
        };
    }
    return value;
}

/**
 * Parse cubic-bezier easing values
 */
function parseCubicBezierValue(value: string): unknown {
    const match = value.match(/cubic-bezier\(([\d.]+),?\s*([\d.]+),?\s*([\d.]+),?\s*([\d.]+)\)/);
    if (match) {
        const [, x1, y1, x2, y2] = match;
        return [parseFloat(x1), parseFloat(y1), parseFloat(x2), parseFloat(y2)];
    }

    const easings: Record<string, number[]> = {
        linear: [0, 0, 1, 1],
        ease: [0.25, 0.1, 0.25, 1],
        "ease-in": [0.42, 0, 1, 1],
        "ease-out": [0, 0, 0.58, 1],
        "ease-in-out": [0.42, 0, 0.58, 1],
    };

    return easings[value] || value;
}

/**
 * Set a value in a nested object structure
 */
function setNestedValue(obj: W3CTokenGroup, path: string[], value: W3CToken): void {
    let current = obj;

    for (let i = 0; i < path.length - 1; i++) {
        const key = path[i];
        if (!(key in current) || typeof current[key] !== "object") {
            current[key] = {} as W3CTokenGroup;
        }
        current = current[key] as W3CTokenGroup;
    }

    const finalKey = path[path.length - 1];
    current[finalKey] = value;
}
